---
- name: Setup Software
  hosts: camp
  become: true
  roles:
    - common
    #- docker
    #- dockerComposeV2
    - role: postgres
      vars:
        postgres_allowed_subnet: 192.168.178.0/24 # Dieses sollte in Prod sehr begrenzt werdenq
        postgres_version: "14"
        postgres_password: "SicheresPasswort123!"
  tasks:
    - name: INIT DB
      become: true
      become_user: postgres
      vars:
        ansible_become_allow_world_readable_tmpfiles: true
      community.postgresql.postgresql_db:
        name: Rumpf
        state: present
    
    - name: update DB
      import_tasks: update.yaml