---
- name: Setup DB
  hosts: camp
  become: true
  roles:
    - common
  tasks:
    - name: Install DB
      role: postgres.install
      vars:
        postgres_version: "0" #
        postgres_allowed_subnet: 192.168.0.0/24 #
        postgres_password: "secure_password"  #
        postgres_admin_db: postgres #
        postgres_user: postgres  #
    
    - name: Init DB
      role: postgres.init
      vars:
        db_name: Rumpf #
        sql_files:
          - /home/ansible/myAnsible/submoduls/CampKraken/Moduls/Rumpf/schema.sql #
          - /home/ansible/myAnsible/submoduls/CampKraken/Moduls/Rumpf/data.sql #
    
    - include_tasks: update.yaml