---
- name: Rechte auf Tabellen vergeben
  community.postgresql.postgresql_privs:
    type: table
    objs: genders,nutritions,shirtSizes,schoolTypes
    roles: "{{ user_dropdown_name }}"
    privs: SELECT
    schema: public

    login_host: 127.0.0.1
    login_user: "{{ pg_user }}"
    login_password: "{{ pg_password }}"
    login_db: "{{ rumpf_db_name }}"
    state: present
